name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the container
      run: docker build -t ${{ secrets.DOCKER_USERNAME}}/car_config Dockerfile
    - name: Run the image with the site
      run: docker run -d -p 80:80 ${{ secrets.DOCKER_USERNAME}}/car_config 
    - name: Deploy ready package
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin;   docker push ${{ secrets.DOCKER_USERNAME }}/car_config:latest

  build_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker image with testing framework
      run: docker build -t ${{ secrets.DOCKER_USERNAME}}/car_config:testing Dockerfile.test
      
  test_action:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Run the image with the site
      run: docker run -d -p 80:80 ${{ secrets.DOCKER_USERNAME}}/car_config:latest
    - name: Run the image with the testing scripts
      run: docker run -d ${{ secrets.DOCKER_USERNAME}}/car_config:testing
